version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: ${NGINX_NAME}
    restart: unless-stopped
    ports:
      - ${NGINX_APP_PORT}:80
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d/
      - ${NGINX_LOG_PATH}:/etc/nginx/logs/
    networks:
      - default
  application:
    build:
      args:
        user: ${APP_USER}
        uid: 1000
      dockerfile: ${DOCKERFILE}
    image: ${APP_NAME}:${APP_TAG}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    working_dir: ${DOCKER_PATH}
    volumes:
      - ${APP_PATH}:${DOCKER_PATH}
    networks:
      - default

networks:
  default:
    name: ${APP_NETWORK}
    external: true