version: "3"
services:
  nginx:
    image: nginx:1.14
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/logs/:/etc/nginx/logs/
      - /e/workspace/ghg-project/:/var/www/html/ghg/
      - /e/workspace/rs-tiara-sella/:/var/www/html/rsts/
      - /e/workspace/technergy-project/:/var/www/html/technergy/
    networks:
      - arfan-net
  redis:
    image: redis:latest
    ports:
      - "6300:6379"
    container_name: redis
    restart: "unless-stopped"
    volumes:
      - ./data/redis:/data
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - arfan-net
  redis_commander:
    image: rediscommander/redis-commander
    ports:
      - "6301:8081"
    container_name: redis_commander
    environment:
      - "REDIS_HOSTS=local:redis:6379"
    restart: "unless-stopped"
    networks:
      - arfan-net
  postgresql:
    image: postgres:13.9
    container_name: postgresql
    hostname: postgres
    ports:
      - "6302:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - arfan-net
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    depends_on:
      -  postgresql
    ports:
      - "6303:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=arfan123
      - PGADMIN_LISTEN_PORT=80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - arfan-net
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    volumes:
      - ./data/mongo:/data/db:rw
    networks:
      - arfan-net
  mongoadmin:
    image: mongo-express
    container_name: mongoadmin
    restart: always
    ports:
      - "6304:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    networks:
      - arfan-net
  mysql_maria:
    image: mariadb:latest
    container_name: mysql_maria
    restart: always
    ports:
      - "6305:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=arfan123
    networks:
      - arfan-net
  mysql_5:
    image: mysql:5.5.62
    container_name: mysql_5
    restart: always
    ports:
      - "6306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=arfan123
    volumes:
      - ./data/mysql/5.5.62:/var/lib/mysql
    networks:
      - arfan-net
  mysql_8:
    image: mysql:8.0.31
    container_name: mysql_8
    restart: always
    ports:
      - "6307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=arfan123
    volumes:
      - ./data/mysql/8.0.31:/var/lib/mysql
    networks:
      - arfan-net
  rabbitmq:
    image: rabbitmq:3.9.27-alpine
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "6308:15672"
      - "6309:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=arfan123
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    networks:
      - arfan-net

networks:
  arfan-net:
    name: arfan-net
    driver: bridge

  