version: "3"
services:
  nodeapp:
    image: "${APP_NAME}:${APP_TAG}"
    env_file: "${ENV_FILE_PATH}"
    networks:
      - default
    ports:
      - "${PORT_APP}:${PORT_APP}"
    restart: unless-stopped

networks:
  default:
    name: ${APP_NETWORK}
    external: true
